CREATE TABLE MEMBER(
  USER_ID NUMBER,
  EMAIL VARCHAR2(255) NOT NULL ,
  PWD VARCHAR2(60) NOT NULL ,
  NAME VARCHAR2(255) NOT NULL ,
  REG_DATE DATE DEFAULT SYSDATE NOT NULL ,
  MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT ''CREATED'' NOT NULL
);


ALTER TABLE MEMBER ADD CONSTRAINT PK_USER PRIMARY KEY(USER_ID);
ALTER TABLE MEMBER ADD CONSTRAINT CK_USER_STATUS CHECK(STATUS IN(''CREATED'', ''UPDATED'', ''DELETED''));


COMMENT ON COLUMN MEMBER.USER_ID IS ''유저ID'';
COMMENT ON COLUMN MEMBER.EMAIL IS ''이메일'';
COMMENT ON COLUMN MEMBER.PWD IS ''비밀번호'';
COMMENT ON COLUMN MEMBER.NAME IS ''유저이름'';
COMMENT ON COLUMN MEMBER.REG_DATE IS ''등록일'';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS ''수정일'';
COMMENT ON COLUMN MEMBER.STATUS IS ''상태'';

CREATE SEQUENCE MEMBER_SEQ NOCACHE;


CREATE TABLE POSTS(
  POSTS_ID NUMBER,
  REG_USER_ID NUMBER,
  MODIFY_USER_ID NUMBER,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT CLOB,
  REG_DATE DATE DEFAULT SYSDATE NOT NULL,
  MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT ''CREATED'' NOT NULL
);

ALTER TABLE POSTS ADD CONSTRAINT PK_POSTS PRIMARY KEY (POSTS_ID);
ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_REG_USER_ID FOREIGN KEY (REG_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_MODIFY_USER_ID FOREIGN KEY (MODIFY_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE POSTS ADD CONSTRAINT CK_POSTS_STATUS CHECK (STATUS IN(''CREATED'',''UPDATED'', ''DELETED''));

COMMENT ON COLUMN POSTS.POSTS_ID IS ''게시판 아이디'';
COMMENT ON COLUMN POSTS.REG_USER_ID IS ''작성자ID'';
COMMENT ON COLUMN POSTS.MODIFY_USER_ID IS ''수정자ID'';
COMMENT ON COLUMN POSTS.TITLE IS ''제목'';
COMMENT ON COLUMN POSTS.CONTENT IS ''내용'';
COMMENT ON COLUMN POSTS.REG_DATE IS ''작성 일자'';
COMMENT ON COLUMN POSTS.MODIFY_DATE IS ''수정 일자'';
COMMENT ON COLUMN POSTS.STATUS IS ''상태'';

CREATE SEQUENCE POSTS_SEQ NOCACHE;


CREATE TABLE COMMENTS (
  COMM_ID NUMBER,
  REG_USER_ID NUMBER,
  MODIFY_USER_ID NUMBER,
  POSTS_ID NUMBER,
  CONTENT VARCHAR2(4000) NOT NULL,
  REG_DATE DATE DEFAULT SYSDATE NOT NULL,
  MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT ''CREATED'' NOT NULL
);

ALTER TABLE COMMENTS ADD CONSTRAINT PK_COMMENT PRIMARY KEY (COMM_ID);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMM_REG_USER_ID FOREIGN KEY (REG_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMM_MODIFY_USER_ID FOREIGN KEY (MODIFY_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMM_POSTS_ID FOREIGN KEY (POSTS_ID) REFERENCES POSTS(POSTS_ID);
ALTER TABLE COMMENTS ADD CONSTRAINT CK_STATUS CHECK (STATUS IN(''CREATED'', ''UPDATED'', ''DELETED''));

COMMENT ON COLUMN COMMENTS.COMM_ID IS ''댓글 아이디'';
COMMENT ON COLUMN COMMENTS.REG_USER_ID IS ''댓글 작성자 아이디'';
COMMENT ON COLUMN COMMENTS.MODIFY_USER_ID IS ''댓글 수정자 아이디'';
COMMENT ON COLUMN COMMENTS.POSTS_ID IS ''게시판 아이디'';
COMMENT ON COLUMN COMMENTS.CONTENT IS ''내용'';
COMMENT ON COLUMN COMMENTS.REG_DATE IS ''작성 일'';
COMMENT ON COLUMN COMMENTS.MODIFY_DATE IS ''수정 일'';
COMMENT ON COLUMN COMMENTS.STATUS IS ''상태'';

CREATE SEQUENCE COMM_SEQ NOCACHE;



CREATE TABLE ATTACHMENT(
  FILE_ID NUMBER,
  POSTS_ID NUMBER,
  USER_ID NUMBER,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  SAVE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(255) NOT NULL,
  FILE_EXT VARCHAR2(10) NOT NULL,
  FILE_SIZE NUMBER,
  FILE_REG_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE ATTACHMENT ADD CONSTRAINT PK_FILE_ID PRIMARY KEY (FILE_ID);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_FILE_POSTS_ID FOREIGN KEY (POSTS_ID) REFERENCES POSTS(POSTS_ID);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_FILE_USER_ID FOREIGN KEY (REG_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE ATTACHMENT ADD (STATUS VARCHAR2(20) DEFAULT ''CREATED'');
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_FILE_STATUS CHECK(STATUS IN(''CREATED'', ''DELETED''));
ALTER TABLE ATTACHMENT ADD (MODIFY_USER_ID NUMBER);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_MODIFY_ID FOREIGN KEY (MODIFY_USER_ID) REFERENCES MEMBER(USER_ID);
ALTER TABLE ATTACHMENT RENAME COLUMN USER_ID TO REG_USER_ID;
ALTER TABLE ATTACHMENT ADD (FILE_MODIFY_DATE DATE DEFAULT SYSDATE);
ALTER TABLE ATTACHMENT MODIFY (STATUS DEFAULT ''CREATED'');

COMMENT ON COLUMN ATTACHMENT.FILE_ID IS ''파일 아이디'';
COMMENT ON COLUMN ATTACHMENT.POSTS_ID IS ''게시판 아이디'';
COMMENT ON COLUMN ATTACHMENT.USER_ID IS ''유저 아이디'';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS ''파일 이름'';
COMMENT ON COLUMN ATTACHMENT.SAVE_NAME IS ''파일 저장 이름'';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS ''파일 저장 경로'';
COMMENT ON COLUMN ATTACHMENT.FILE_EXT IS ''파일 확장자'';
COMMENT ON COLUMN ATTACHMENT.FILE_SIZE IS ''파일 크기'';
COMMENT ON COLUMN ATTACHMENT.FILE_REG_DATE IS ''파일 등록일'';

CREATE SEQUENCE FILE_SEQ NOCACHE;



CREATE OR REPLACE
  FUNCTION GET_ACCESS_ID
RETURN
    NUMBER AS num NUMBER;
BEGIN
  SELECT FILE_SEQ.NEXTVAL
    INTO NUM
    FROM DUAL;
    RETURN NUM;
END;


COMMIT;