INSERT INTO MEMBER
    VALUES(MEMBER_SEQ.nextval, 'ADMIN', 'ADMIN', '관리자', SYSDATE, SYSDATE, DEFAULT );


INSERT INTO MEMBER
    VALUES(MEMBER_SEQ.NEXTVAL, 'USER', 'USER', '사용자', SYSDATE, SYSDATE, DEFAULT );

SELECT * FROM MEMBER;

INSERT INTO POSTS
    VALUES(POSTS_SEQ.NEXTVAL, 2, 2, '테스트', '테스트', SYSDATE, SYSDATE, DEFAULT );

SELECT * FROM POSTS;


INSERT INTO COMMENTS
    VALUES (COMM_SEQ.NEXTVAL, 1, 1, 2, 'COMMTEST2', SYSDATE, SYSDATE, DEFAULT );

SELECT * FROM COMMENTS;

SELECT * FROM ATTACHMENT;

INSERT INTO ATTACHMENT
    VALUES (FILE_SEQ.NEXTVAL, 2, 1, 'ORGIN_NAME', 'SAVE_NAME', 'PATH', '.EXT', 112233, SYSDATE);

COMMIT;

SELECT * FROM POSTS
WHERE STATUS != 'DELETED'
AND INSTR(TITLE, 'A') > 0
OR INSTR(CONTENT, 'A') > 0;

SELECT A.*,
    B.NAME
FROM POSTS A
JOIN MEMBER B ON(A.REG_USER_ID = B.USER_ID);

SELECT A.*,
    M.NAME AS "M_USER",
    C.NAME AS "C_USER"
FROM POSTS A
JOIN MEMBER M on A.MODIFY_USER_ID = M.USER_ID
JOIN MEMBER C ON A.REG_USER_ID = C.USER_ID
WHERE A.STATUS != 'DELETED'
AND M.NAME = '사용자';

SELECT * FROM POSTS
WHERE INSTR(UPPER(TITLE), UPPER('테스트')) > 0;


SELECT * FROM POSTS;

SELECT * FROM ATTACHMENT;

SELECT * FROM POSTS
WHERE STATUS != 'DELETED'
AND REG_DATE BETWEEN TO_DATE('2021-08-18', 'RRRR-MM-DD') AND TO_DATE('2021-08-20', 'RRRR-MM-DD');


SELECT
       A.POSTS_ID
     , B.NAME AS "REG_NAME"
     , C.NAME AS "MODIFY_NAME"
     , A.TITLE
     , A.CONTENT
     , A.REG_DATE
     , A.MODIFY_DATE
     , A.STATUS
FROM POSTS A
LEFT OUTER JOIN MEMBER B ON(A.REG_USER_ID = B.USER_ID)
LEFT OUTER JOIN MEMBER C ON(A.MODIFY_USER_ID = C.USER_ID)
WHERE A.STATUS != 'DELETED'
AND UPPER(B.NAME) = UPPER('사용자');


SELECT A.*
, P.*
    FROM ATTACHMENT A
JOIN POSTS P on A.POSTS_ID = P.POSTS_ID
WHERE A.POSTS_ID = 2;


UPDATE POSTS
SET MODIFY_DATE = SYSDATE
WHERE POSTS_ID = 26;




INSERT ALL
  INTO ATTACHMENT(FILE_ID, POSTS_ID, REG_USER_ID
                , MODIFY_USER_ID, ORIGIN_NAME, SAVE_NAME
                , FILE_PATH, FILE_EXT, FILE_SIZE
                , FILE_REG_DATE, FILE_MODIFY_DATE, STATUS)
VALUES(GET_ACCESS_ID(), 12, 1, 1, 'api 문서.xlsx', 'cd09d98c5bcc4599ba797320d32b8ad1.xlsx'
            , 'path', '.xlsx', 21211, SYSDATE, SYSDATE, DEFAULT )
INTO ATTACHMENT
VALUES(GET_ACCESS_ID(), 12, 1, 1, 'api 문서.xlsx', 'cd09d98c5bcc4599ba797320d32b8ad1.xlsx'
            , 'path', '.xlsx', 21211, SYSDATE, SYSDATE, DEFAULT )
SELECT * FROM dual;

COMMIT;


 SELECT
              COMM_ID
            , REG_USER_ID
            , MODIFY_USER_ID
            , CONTENT
            , REG_DATE
            , MODIFY_DATE
            , STATUS
        FROM COMMENTS
        WHERE STATUS != 'DELETED'
        AND   POSTS_ID = 41;